### ISSUE TITLE
Node Version Mismatch Error

### ISSUE THREAD

**Issue by shkesar** [therishabhpandey/snippeteer#3]
Got this error message when hitting enter key after search for a snippet.

![image](https://user-images.githubusercontent.com/5822067/38581012-2a430c2c-3d29-11e8-8fd8-3ca6e3340227.png)

**Comment by rishpandey** [comment]
Did you download a copy or using a build?

**Comment by shkesar** [comment]
I built it on my machine. Now I know it was because of the instruction I missed in the README about post install step. Anyways, I figured out an alternative before I saw that.

**Comment by shkesar** [comment]
I'll close this after a pull request to automate this.

**Comment by shkesar** [comment]
#4
